name: Build custom props

on:
  workflow_dispatch:

jobs:
  build:
    name: Build props
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install APT packages
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: dos2unix python3 python3-pip zip

      - name: Install protobuf
        run: |
          pip install --upgrade pip
          pip3 install -Iv protobuf==3.20.3

      - name: Make all scripts executable
        run: chmod +x *.sh

      - name: Download build from secrets
        env:
          LINK: ${{ secrets.LINK }}
        if: ${{ env.LINK != null}}
        run: |
          mkdir dl
          cd dl
          wget -O "image.zip" ${{ env.LINK }}

      - name: Extract images and build
        id: extract_and_build
        run: ./extract_images.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.extract_and_build.outputs.module_base_name }}
          path: result
          if-no-files-found: error
